export const ApibaseURL = import.meta.env.VITE_API_BASE_URL;
export const Baseurl = import.meta.env.VITE_API_BASE_URL;
export const loginApi = "signin"
export const registerApi = "signup"
export const productApi = "getAllproducts"
export const addToCartApi ="addToCart"
export const addToWishlistApi ="addToFavorites"
export const getWishlistApi ="getFavorites"
export const removeWishlistApi = "removeFromFavorites"
export const getCartlistApi = 'getCart'
export const updateQuantityApi = 'updateCartItemQuantity'
export const getCategoryApi = 'getCategories'
export const createOrderApi ='createorder'
