export const BasePath = '/'
export const HomePath='home'
export const WishlistPath= 'wishlist'
export const ProfilePath = 'profile'
export const ProductsPath= 'products'
export const CartPath = 'cart'
export const LoginPath = 'login'
export const RegisterPath ='register'